pkg/database/dgraph.go
pkg/master/master.go

Node's name is set to the basename of its path. This is for displaying
only. Do not expect this to be unique.

Add name to Node

---

pkg/analysis/spdx.go
pkg/database/dgraph.go

Do not return error if file was not found and break the whole analysis.
Print a warning and set the unknown license.

Fix spdx analyzer

---

cmd/qmstr/qmstr.go

For the moment, this generates the instrumentation bin/ directory, prepends it to the path, and then executes the build commands. 
In a next step, this should also start the master and propagate the IP address and port.
References QMSTR/qmstr-all#37.

Implement "easy mode" by introducing the qmstr tool

---

cmd/qmstr/qmstr.go

This makes shells work as expected (as in `qmstr bash`).

Also pass stdin to the wrapped command

---

pkg/database/dgraph.go

Fixes deadlock when too many nodes are submitted very fast the insert
queue buffer fills to the maximum capacity and locks the insert routine
when trying to put back a node, that is not yet ready, to the queue.

Fix deadlock if queue filled up to the maximum.

---

cmd/qmstr-wrapper/main.go
cmd/qmstr/qmstr.go
pkg/cli/root.go
pkg/cli/wait.go

Add the option to connect to a provided address. Default is localhost:50051.
qmstr-cli also listens to the address provided by the flag 'cserv'
Needed for our demo cases

Add option to connect wrapper and cli to different address

---

pkg/wrapper/fileutil.go

Add /lib64 to the library lookup pathes. This is where e.g. opensuse
tumbleweed stores system libraries for 64-bit systems.

Find libraries in /lib64

---

ci/Dockerfile
ci/scancode.requirements
cmd/analyzers/scancode-analyzer/main.go
pkg/analysis/analyzer.go
pkg/database/dgraph.go
pkg/master/analyze.go
pkg/master/master.go
pkg/master/report.go

When scancode fails to read a file it returns a non-zero return code even though a scan result is produced that can be used. To work around this behavior we do not only check the return code but the status message from stderr as well.

fix scancode analyzer

---

cmd/qmstr/qmstr.go

It points to where the bin/ directory is that contains the wrapper links.

Export environment variable QMSTR_INSTRUMENTATION_HOME.

---

Gopkg.lock
Gopkg.toml
ci/Dockerfile
install.sh

The golang protobuf compiler plugin changed and therefor the new protobuf lib is needed to compile the generated code.

hotfix protobuf deps

---

Makefile
ci/Dockerfile

Speed up pexing in dev container by using grpcio python wheel to avoid recompiling the grpc C code.

speedup pex

---

cmd/qmstr-wrapper/main.go
pkg/cli/root.go

Setup logging via init. Otherwise SIGSEGV will be the result when
providing unknown flag duei access to uninitialized logger.

Fix qmstrctl logging setup

---

Makefile

If no GOPATH environment variable is set, the default is ~/go. ¨go env GOPATH¨ will report it.

Make the Makefile make files if no GOPATH is set (which is ok).

---

pkg/cli/start.go

set the right address variable to wait for the master on start command

fix wait when starting

---

pkg/reporter/htmlreporter/htmlreporter.go
pkg/reporter/htmlreporter/share/templates/site-index.md
pkg/reporting/reporter.go

With this, the content from different projects and revisions will be aggregated in a site, as long as the cache lives.

Make the HTML reporter use the cache directory for content

---

cmd/analyzers/pkg-analyzer/main.go
pkg/config/config.go
pkg/master/analyze.go
proto/analyzerservice.proto

Package analyzer connects the package node with linked targets but in the case of jabref we
want to connect the package node to a jar file. In that case we provide a type selector to
override the default type.

Check type selector in the configuration

---

pkg/cli/phasecontrol.go
pkg/master/analyze.go
pkg/master/master.go
pkg/master/report.go
proto/controlservice.proto

Print out better failure messages and publish more events to improve
feedback to the user.

Distinguish between rpc failure and modules failure

---

pkg/module/reporter/htmlreporter/htmlreporter.go

At least the version installed by Homebrew does not contain the
"BuildDate" part in the version string anymore.

Fix Hugo dectection in latest versions.

---

ci/test-documentation.sh
doc/Getting-Started.md

"Getting started" needs to be tested after "installation". It expects the tools to be installed.

Fix the order of the doc tests.

---

pkg/cli/copy.go
pkg/cli/quit.go
pkg/cli/start.go
pkg/config/config.go
pkg/config/config_test.go
pkg/docker/copy.go
pkg/master/analyze.go
pkg/master/constants.go
pkg/master/report.go

Moving results to host on quit.
WARN:This redefines outputdir in qmstr.yaml to be the host destination!
refs https://github.com/QMSTR/qmstr-all/issues/104

moving output to host

---

ci/Jenkinsfile

Since Jenkins does not do it by default... which is weird.

Add a step to force cleaning the repository before starting.

---

ci/Vagrantfile

This fixes the crashes in the analysis phase of the tutorials in the
doc tests. The VM runs out of memory.

Increase Vagrant VM memory with Virtualbox.

---

ci/Jenkinsfile

Otherwise, git skips repositories, and leaves our `json-c` example
repo in place.

Use the super strict form of "git clean" to get really clean.

---

ci/common.inc
cmd/qmstr-master/main.go
pkg/cli/copy.go
pkg/cli/start.go
pkg/config/config.go
pkg/config/config_test.go
pkg/docker/copy.go

Implement using multiple configuration files to use the host specific configuration /etc/qmstr/qmstr.yaml .
This makes setting a cachedir (host specific) possible.
closes https://github.com/QMSTR/qmstr-all/issues/98

global config

---

cmd/qmstr/qmstr.go

Qmstr now returns error if payload commands do not finish successfully
Issue: https://github.com/QMSTR/qmstr-all/issues/116

Catch other errors apart from ExitError in qmstr easy mode

---

cmd/modules/analyzers/pkg-analyzer/main.go
cmd/modules/analyzers/test-analyzer/main.go
pkg/cli/start.go
pkg/common/fileutil.go
pkg/config/config.go
pkg/gccbuilder/gcc-builder.go
pkg/master/analyze.go
pkg/master/build.go

Use relative paths to workdir/builddir instead of the absolute path.
No need to store the absolute path.
Get rid of the ugly /buildroot from the path.
closes QMSTR/qmstr-all/issues/91

Use relative paths

---

pkg/cli/start.go

Enable option to specify the time we want to wait for qmstr-master with the timeout flag.

Add timeout flag for wait when it's called from start command

---

Makefile
ci/Dockerfile

Do not recalculate dependencies if this has been done before.

Use the resolved Gopkg.lock

---

ci/Dockerfile

Use RUN apt-get update with apt-get install in the same RUN to avoid cashing issues and subsequently avoid apt-get install to fail.

Combine RUN apt-get update with install

---

ci/Dockerfile

Installing PyICU needs the version of libicu to use.
Closes https://github.com/QMSTR/qmstr-all/issues/167

Set ICU_VERSION env to fix installing PyICU

---

pkg/database/fileNode.go
pkg/master/analyze.go
pkg/master/common.go

GetFileNodesByFileNode used to query only fileTypes. 
Now it is more generic and it can support other queries.

Refactor GetFileNodesByFileNode to support other queries apart from fileType

---

proto/qmstr/service/bom.proto

This field is to be set by the user (or tool?) in the "metadata" section
of the QMSTR yaml config file and it should point to the source of the
package being analyzed
For example:
* http://ftp.gnu.org/gnu/glibc/glibc-ports-2.15.tar.gz
* git://git.myproject.org/MyProject

Add sourceURL field in PackageInformation

---

doc/Installation.md

I have gathered the information that was useful to me to install properly Quartermaster and add it to the Installation file,  so next time somebody wants to install Quartermaster will find all the clues on it and will only need to follow this instructions.

Add More information to the Installation document

---

pkg/cli/snapshot.go

If a snapshot with the same name exists then the new snapshot used to be appended to the existing one.  --> corrupted snapshot
To avoid that, we remove the snapshot before creating the new one.

Fix snapshot

---

pkg/reporting/revision_data.go

If commit message includes \ it will break the parser.
The fix for that would be to replace it with \\\\

Fix html reporter commit message

---

ci/Vagrantfile

Scancode eats RAM so double available RAM to 4GB.

Increase VMs memory for scancode

---

pkg/database/infoNode.go

The else block is misleading when adding info nodes.
Check for fileNodeType and in the end produce an error.
This way it will become clear.

Make if else statement clearer

---

pkg/cli/idparsing.go
pkg/cli/idparsing_test.go

Parse node identifications and return nodes with the desired value set.
This will be used to query the actual node from the database.
For now only file and package nodes are supported.
refs https://github.com/QMSTR/qmstr-all/issues/188

Add node identification parsing mechanism

---

doc/content/qmstr-basics/_index.md
doc/content/qmstr-basics/qmstr-cli/_index.md
doc/content/qmstr-basics/qmstr-cli/database_cmds/_index.md
doc/content/qmstr-basics/qmstr-cli/database_cmds/connect/_index.md
doc/content/qmstr-basics/qmstr-cli/database_cmds/create/_index.md
doc/content/qmstr-basics/qmstr-cli/database_cmds/delete/_index.md

closes https://github.com/QMSTR/qmstr-all/issues/203
The CRUD commands will be seperated, in the documentation, from the rest qmstrctl commands
in the `Database commands` subdirectory.
This is just a first commit, including only a short description of the referenced nodes.

A first commit about qmstr commands documentation

---

pkg/master/report.go
pkg/reporting/bom.go

Pass the project node to the BOM generation functions to pick up
metadata that was stored in package node before.

Pass project node to BOM generation

---

doc/content/introduction/getting-started/_index.md
doc/content/introduction/installation/_index.md
pkg/cli/version.go
pkg/module/reporter/htmlreporter/htmlreporter.go

The QMSTR version is currently listed in a couple of places. This PR updates it. Long-term, we should have a central way to specify the version and import it across the different toolchains and programming languages used.

Update QMSTR version in the documentation and the code

---

.gitignore
pkg/module/reporter/htmlreporter/htmlreporter.go

Introduces generateStatics option where:
- the tar package is generated with the entire hugo workdir
- Or it builds the static files and then saves to the tar package
Closes #260
Depends https://github.com/QMSTR/qmstr-demo/pull/64

Introduce an option to generate hugo site

---

doc/content/reference/_index.md
lib/go-qmstr/cli/dev-generate-reference.go

This is an option primarily aimed at developers, hence the tedious command "dev-generate-reference".

Generate the command line reference for qmstrctl.

---

lib/go-qmstr/database/dgraph.go
lib/go-qmstr/database/dgraph_test.go
lib/go-qmstr/database/infoNode.go
lib/go-qmstr/docker/client.go
lib/go-qmstr/master/report.go
masterserver/Dockerfile
masterserver/Makefile.common
modules/analyzers/spdx-analyzer/Makefile.common
modules/analyzers/spdx-analyzer/setup.py
modules/analyzers/spdx-identifier-analyzer/main.go

closes https://github.com/QMSTR/qmstr-all/issues/97
This PR just creates the query which uses the trust level and returns the most trustworthy data.
We do not query for the data type yet.
Query is not yet used by reporters. We discussed a restructure of the code, to extract bom as a library, and make calls to the db on specific node types (not just query for a package node and traverse on it).

Include TrustLevel in InfoNode query

---

doc/Makefile.common

A simple Makefile extension that adds the command line reference to the web tarball.

Add command line reference generating to the documentation step.

---

lib/go-qmstr/cli/wait.go
lib/go-qmstr/docker/client.go

Cancel the connection timeout because it is not useful to wait for the
whole insert queue to be done in 60 seconds.

[qmstrctl] cancel timeout if only waiting for inserts

---

ci/vagrant-bootstrap.sh
doc/content/introduction/getting-started/_index.md
doc/content/introduction/getting-started/tutorial/build-json-c.sh
doc/content/introduction/installation/_index.md
lib/go-qmstr/config/config.go
lib/go-qmstr/config/config_test.go
lib/go-qmstr/config/validation.go

Sanitization of the configuration was not working due to copy by value.
This also fixes the default trustlevel being 1 instead of 0, to make sure it is serialized and written to database.

Fix config

---

doc/Makefile.common

The dependencies are the actual binaries to be called.

Fix documentation dependencies

---

lib/go-qmstr/pkg/package.go
lib/go-qmstr/pkg/package_test.go

This change introduces 2 new interfaces. Manifest and Package.
* Manifest is for abstracting documents like SPDX
* Package is for abstracting archives like deb, jar, etc.
In combination they can be used to validate arbitrary packages against
arbitrary manifests.

Introduce package abstraction

---

lib/go-qmstr/cli/update.go
lib/go-qmstr/master/master.go
lib/go-qmstr/service/common.go
lib/go-qmstr/service/common_test.go

Check for an empty package before returning all package nodes. Checking
for valid package node will fail whenever there is only name or version
provided in the query node.

HOTFIX [master] check for empty package on query

---

doc/content/WIP/validation/_index.md

* The reporter will be called the _package manifest reporter_.
* Only Debian packages are on the 0.6 roadmap.

Update the validation feature spec.

---

lib/go-qmstr/reporting/package_data.go
lib/go-qmstr/service/common.go
modules/reporters/qmstr-reporter-html/package_reports.go
modules/reporters/qmstr-reporter-html/share/skeleton/layouts/shortcodes/target-list.html

Now the HTML Reporter uses the common function `RemoveSlash` to replace it with an underscore in packages and project names, preventing the creation of subfolders and inconsistencies between file structures and references inside Hugo building phase.
_A suggestion for the future is to update this function to remove any kind of special character across phases, to prevent related bugs._
It was also added a Hugo function to wrap arrays, making sure that Hugo can build properly even if it's an empty array.
<br>
Fix #382, fix #385

Prevent HTML failures with slashes '/' and empty arrays

---

modules/packages/deb.go

The previous implementation of deb package was ignoring only directories.
This change checks only for regular files to avoid situations that the
file in check is a symbolic link that might or might not point to a file
in the archive.

[deb pkg] Validate only regular files.

---

lib/pyqmstr/qmstr/module/utils.py
modules/builders/qmstr-py-builder/qmstrpybuilder/bdistbuilder.py

Use absolute paths to make sure path substitution works.

absolute paths in python

---

lib/go-qmstr/database/dgraph.go

We forgot to retrieve the target's filedata when adding a package node.
Also for a dependency if filedata doesn't exist in the database,
then the node should be put back in the insert queue.

Fix: Check if filedata already exists in db

---

lib/go-qmstr/database/diagnosticNode.go
lib/go-qmstr/database/fileNode.go

On order to remove the fileType field in file nodes we need to query for
source file nodes. This information is already in the graph. Every leaf
filenode is considered a source as it was not derived from other
filenodes.
closes #280

280 leaves query

---

lib/go-qmstr/cli/start.go

We should be able to define the container image we want to run the
qmstr master, through the command line when we start the qmstr master.

[start cmd] Add a string flag to define a different image name

---

.gitmodules
Jenkinsfile
Makefile

we want to reduce the requirements on the build environment so a docker image was created at endocode/qmstr_buildenv which will be used by the CI to test & build qmstr. Artifacts are stored & published on endocodes CI system.
The demo repository is now linked into the parent repository so there is a defined state of application & test environment

add ci config & tests

---

modules/analyzers/scancode-analyzer/main.go

closes #431 
If for a file node scancode does not detect license/copyright information,
then it should skip creating an info message for this file node.

Scancode should not create empty info messages

---

lib/go-qmstr/reporting/package_data.go
modules/analyzers/spdx-analyzer/spdxanalyzer/__main__.py
modules/reporters/qmstr-reporter-html/package_reports.go
modules/reporters/qmstr-reporter-html/share/skeleton/layouts/shortcodes/copyrights.html
modules/reporters/qmstr-reporter-html/share/templates/version-index.md

Fix #318
_PS: it only shows up in HTML reporter if we raise the spdx-analyzer `trustlevel`. Created #395 to improve this behavior._
Originally from #389

Add SPDX copyright data to file nodes

---

lib/go-qmstr/database/packageNode.go

Update the query to also return the file hash from FileDataNode
fix #447

[database] Return file node hash

---

modules/analyzers/spdx-analyzer/spdxanalyzer/__main__.py

Remove python2 from spdx-analyzer.
Even though we are using an old version of the python spdx-tool lib (v0.5.4) as a dependency, we don't need python 2 anymore because all indirect dependencies were updated to support python 3+.
<br>
fix #453

Update python version

---

modules/reporters/qmstr-reporter-html/htmlreporter.go

We had this check before but this commit removed it: https://github.com/QMSTR/qmstr/pull/441/commits/82506319ad31b76d078040d184387751dcf10549

Html reporter should not fail when there are no package nodes 

---

.dockerignore
docker/qmstr-master/Dockerfile

Provides a minimal qmstr-master docker image to be used in later stages (i.e. by new CI, Kubernetes manifests, etc.).
To verify basic functionality, provide a qmstr.yaml configuration either as docker command or k8s argument and reference an accessible dgraph endpoint.
E.g.:
```bash
docker build -f docker/qmstr-master/Dockerfile -t qmstr/master:latest .
cd /tmp
mkdir ./config
cat << EOF > /tmp/config/qmstr.yaml
project:
name: "HelloWorld"
metadata: 
message: "Hello World!" 
EOF
cat << EOF > docker-compose.yaml
version: "3.7"
services:
dgraph:
image: dgraph/standalone:latest
ports:
- 9080:9080
networks:
- qmstr
master:
image: qmstr/master
depends_on:
- dgraph
ports:
- 50051:50051
networks:
- qmstr
environment:
SERVER_DBADDRESS: dgraph:9080
volumes:
- /tmp/config:/home/qmstr/config
command: …
```

Strip qmstr-master image
