QMSTR/qmstr

- cmd/qmstr-master/main.go
- cmd/qmstr-wrapper/main.go
- pkg/buildservice/buildservice.proto
- pkg/compiler/compiler.go
- pkg/compiler/gcc-compiler.go
- pkg/compiler/gcc-compiler_test.go
- pkg/wrapper/wrapping.go
Add functionality to analyze gcc commandline, create a BuildMessage and
send it to the master server.
> Add gcc compiler analysis

- pkg/wrapper/fileutil.go
Check first in LD_LIBRARY_PATH for libraries
https://github.com/QMSTR/qmstr-all/issues/16
> Include LD_LIBRARY_PATH in library lookup

- README.md
- install.sh
There is no qmstr-client anymore, welcome qmstr-cli.
> Fix install

- pkg/compiler/gcc-compiler.go
Make json-c compile on gcc on macOS
> macos fixes

- README.md
Embed build status in the repository README.
> Embed build status in README.

- README.md
The build status plugin seems to be behind regarding this.
> Updating the URL since it has changed in Jenkins.

- pkg/analysis/ninka.go
- pkg/master/master.go
Add ninka analysis for license detection.
Issue: https://github.com/QMSTR/qmstr-all/issues/12
> Add Ninka analyzer

- ci/Dockerfile
- ci/dev-entrypoint.sh
Run the master server via dlv to remotely debug it if QMSTR_DEV is set.
> Start debugger if QMSTR_DEV is set

- pkg/analysis/analyzer.go
- pkg/analysis/scancode.go
- pkg/database/dgraph.go
Issue: https://github.com/QMSTR/qmstr-all/issues/15
> Find copyright holders with scancode

- pkg/master/master.go
- pkg/report/copyrightHolder.go
Add and implement copyright holders report generation depended on the graph.
> Add copyright holders report

- README.md
- ci/dev-entrypoint.sh
Explain how to start qmstr development container to debug qmstr-master.
> Add debugging explanation

- cmd/analyzers/scancode-analyzer/main.go
Detect authors apart from copyright holders.
> Add author detection with scancode

- cmd/qmstr-reporter-html/main.go
Multiple locations are required to support restrictions on the master host system. For example, on some systems, /usr/share is immutable. The locations at the moment are /usr/share/qmstr, /usr/local/share/qmstr, and /opt/share/qmstr (in that order).
The functions are written to be reusable and will be refactored into the common package for all modules.
> Introduce variable locations for the shared data directory

- ci/Dockerfile
Added binaries and gopath for demo purposes.
> Create demo cases in container

- pkg/reporter/htmlreporter/htmlreporter.go
- pkg/reporting/reporter.go
> Fix error handling of reporters

- cmd/analyzers/scancode-analyzer/main.go
- cmd/analyzers/spdx-analyzer/main.go
- cmd/qmstr-reporter-html/main.go
- pkg/analysis/analyzer.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/master/analyze.go
- pkg/master/master.go
- pkg/master/report.go
- pkg/reporting/reporter.go
- pkg/service/analyzerservice.proto
- pkg/service/reportservice.proto
Introduce cached data directory
> 56 cache data dir

- cmd/analyzers/pkg-analyzer/main.go
- cmd/analyzers/scancode-analyzer/main.go
- cmd/analyzers/spdx-analyzer/main.go
- cmd/analyzers/test-analyzer/main.go
- install.sh
- pkg/analysis/analyzer.go
- pkg/compiler/gcc-compiler.go
- pkg/database/dgraph.go
- pkg/master/analyze.go
- pkg/master/build.go
- pkg/master/master.go
- pkg/master/report.go
- pkg/reporting/reporter.go
- pkg/service/common.go
- proto/analyzerservice.proto
- proto/controlservice.proto
- proto/datamodel.proto
- proto/reportservice.proto
- python/spdx-analyzer/spdxanalyzer/__main__.py
Create new package analyzer that connects configured targets with the package node
Issue: https://github.com/QMSTR/qmstr-all/issues/74
> Package analyzer

- pkg/compiler/gcc-compiler.go
Noticed extra flags while compiling openssl.
> Insert extra gcc flags

- pkg/master/master.go
Switching phase is not allowed during a pending phase switch.
> Protect switching phase

- cmd/qmstr/qmstr.go
qmstr now uses pflag as the rest of QMSTR.
Ticket: https://github.com/QMSTR/qmstr-all/issues/38
> #38 Change easymode to use pflags 

- cmd/analyzers/test-analyzer/main.go
- pkg/database/dgraph.go
- pkg/master/analyze.go
- pkg/service/common.go
Now we can provide the test we want to run through the configuration.
> Insert more tests in test analyzer

- pkg/config/config.go
- pkg/master/analyze.go
- proto/datamodel.proto
Trust levels are configured and assigned to analysis modules to
specify each module's reliability.
> #59 Trust levels for modules

- .gitignore
- cmd/analyzers/pkg-analyzer/main.go
- cmd/analyzers/scancode-analyzer/main.go
- cmd/analyzers/spdx-analyzer/main.go
- cmd/analyzers/test-analyzer/main.go
- pkg/analysis/analyzer.go
- python/pyqmstr/pyqmstr/module/module.py
- python/spdx-analyzer/spdxanalyzer/__main__.py
> 62 spdx packagedata

- Makefile
- pkg/database/dgraph.go
- pkg/master/analyze.go
- pkg/master/common.go
- pkg/master/master.go
- proto/analyzerservice.proto
introduce functionality to send info nodes
> 83 sending infonodes

- .gitignore
- Makefile
- ci/Dockerfile
- cmd/analyzers/git-analyzer/main.go
- cmd/analyzers/pkg-analyzer/main.go
- cmd/analyzers/scancode-analyzer/main.go
- cmd/analyzers/spdx-analyzer/main.go
- cmd/analyzers/test-analyzer/main.go
- cmd/reporters/test-reporter/main.go
- install.sh
- pkg/analysis/analyzer.go
- pkg/database/dgraph.go
- pkg/master/analyze.go
- pkg/master/common.go
- pkg/master/master.go
- pkg/master/report.go
- pkg/reporter/htmlreporter/htmlreporter.go
- pkg/reporting/reporter.go
- proto/analyzerservice.proto
- proto/controlservice.proto
- proto/datamodel.proto
- proto/reportservice.proto
- python/pyqmstr/pyqmstr/module/module.py
- python/spdx-analyzer/spdxanalyzer/__main__.py
Test it with: https://github.com/QMSTR/qmstr-demo/pull/39
> Implement git analyzer

- cmd/analyzers/git-analyzer/main.go
Issue: https://github.com/QMSTR/qmstr-all/issues/92
> Return error if working dir is not configured

- cmd/analyzers/pkg-analyzer/main.go
Package analyzer detects regular expressions provided in the configuration.
> Add regular expression handling in package analyzer

- cmd/modules/analyzers/test-analyzer/main.go
Test analyzer panics as it tried to access array data that didn't exist.
Issue: https://github.com/QMSTR/qmstr/issues/115
> Fix test analyzer runtime error

- pkg/cli/log.go
- pkg/cli/start.go
This allows printing out master logs.
> Add logs command to qmstrctl

- pkg/module/reporter/htmlreporter/share/skeleton/layouts/shortcodes/target-list.html
- pkg/reporting/bom.go
- proto/bom.proto
Add the dependencies to the bill of material and render it to html
report.
> Add dependencies to BOM and htmlreporter

- README.md
- ci/Vagrantfile
- ci/test-documentation.sh
- ci/vagrant-bootstrap.sh
- ci/vagrant-test-documentation-driver.sh
- doc/Developers.md
- doc/Installation.md
> Update installation instructions and main README.

- ci/Jenkinsfile
adding a basic jenkinsfile in ci/ folder
this should be extended to include the remaining
parts of the test suite.
> add jenkinsfile

- README.md
More CI means more badges. Fun.
> Embed doc test results in README.

- ci/vagrant-bootstrap.sh
- doc/Getting-Started.md
...and use HTTPS for downloads.
> Install tutorial dependencies

- pkg/cli/start.go
Exit if not.
fixes #https://github.com/QMSTR/qmstr-all/issues/117
> Check if supplied qmstr.yaml exists

- cmd/modules/analyzers/scancode-analyzer/main.go
- pkg/module/reporter/htmlreporter/share/skeleton/layouts/shortcodes/target-list.html
- pkg/module/reporter/htmlreporter/share/skeleton/static/css/theme-mine.css
- pkg/module/reporter/htmlreporter/share/templates/config.toml.in
closes https://github.com/QMSTR/qmstr-all/issues/118
> 118 show license name

- Makefile
- ci/Dockerfile
- ci/deploy-ratel.sh
- ci/ratel-entrypoint.sh
- pkg/gccbuilder/gcc-builder.go
- pkg/gccbuilder/gcc-builder_test.go
- pkg/module/reporter/htmlreporter/share/skeleton/layouts/shortcodes/target-list.html
> diverse changes

- ci/deploy-ratel.sh
- ci/recentMaster.sh
- cmd/qmstr-wrapper/main.go
- cmd/qmstr/qmstr.go
- pkg/cli/start.go
- pkg/common/constants.go
- pkg/docker/client.go
Allow enabling debug output in build containers
> build container debugging

- Makefile
- ci/Dockerfile
Improve makefile and dockerfile to speed up rebuilds
> makefile improved

- pkg/module/reporter/htmlreporter/share/skeleton/layouts/shortcodes/target-list.html
closes https://github.com/QMSTR/qmstr-all/issues/122
> Use author information from scancode in reports

- cmd/qmstr/qmstr.go
- pkg/gnubuilder/asbuilder/asbuilder.go
- pkg/gnubuilder/asbuilder/asbuilder_test.go
- pkg/gnubuilder/common.go
- pkg/gnubuilder/flags.go
- pkg/wrapper/wrapping.go
Add basic structure to wrap the as assembler 
Closes https://github.com/QMSTR/qmstr-all/issues/127
> Wrap as assembler 

- pkg/database/dgraph.go
- pkg/master/analyze.go
- pkg/master/build.go
closes https://github.com/QMSTR/qmstr-all/issues/133
> reopeninsertqueue

- cmd/modules/analyzers/missing_pieces-analyzer/main.go
- cmd/modules/analyzers/pkg-analyzer/main.go
- pkg/builder/builder.go
- pkg/common/fileutil.go
- pkg/database/dgraph.go
- pkg/database/fileNode.go
- pkg/database/packageNode.go
- pkg/master/analyze.go
- pkg/master/build.go
- pkg/master/common.go
- pkg/master/init.go
- pkg/master/master.go
- proto/qmstr/service/analyzerservice.proto
Closes https://github.com/QMSTR/qmstr-all/issues/132
Closes https://github.com/QMSTR/qmstr-all/issues/134
Test it with https://github.com/endocode/siemens_compliance/pull/5
> Missing pieces analyzer

- cmd/modules/analyzers/missing_pieces-analyzer/main.go
Actually send the provided filenodes
> Let missing pieces analyzer actually send something

- java/gradle/build.gradle
- java/gradle/src/main/java/org/qmstr/util/FilenodeUtils.java
Closes https://github.com/QMSTR/qmstr-all/issues/137
> Fix gradle plugin after database refactoring 

- cmd/modules/analyzers/pkg-analyzer/main.go
- pkg/common/fileutil.go
- pkg/database/dgraph.go
- pkg/database/dgraph_test.go
- pkg/database/fileNode.go
- pkg/master/analyze.go
> files generated from itselves

- pkg/database/dgraph.go
- pkg/database/dgraph_test.go
> Remove space from schema to fit the exported schema

- pkg/objcopybuilder/objcopybuilder.go
> Change binary type

- cmd/modules/analyzers/pkg-analyzer/main.go
- cmd/qmstr-wrapper/main.go
- pkg/arbuilder/arbuilder.go
- pkg/builder/builder.go
- pkg/cli/snapshot.go
- pkg/common/constants.go
- pkg/common/fileutil.go
- pkg/common/fileutil_test.go
- pkg/docker/copy.go
- pkg/gnubuilder/asbuilder/asbuilder.go
- pkg/gnubuilder/common.go
- pkg/gnubuilder/gccbuilder/gcc-builder.go
- pkg/gnubuilder/gccbuilder/gcc-builder_test.go
- pkg/gnubuilder/ldbuilder/ld-builder.go
- pkg/gnubuilder/ldbuilder/ld-builder_test.go
- pkg/master/build.go
- pkg/master/common.go
- pkg/master/init.go
- pkg/master/master.go
- pkg/objcopybuilder/objcopybuilder.go
- pkg/wrapper/wrapping.go
- proto/qmstr/service/buildservice.proto
- proto/qmstr/service/controlservice.proto
closes https://github.com/QMSTR/qmstr-all/issues/139
closes https://github.com/QMSTR/qmstr-all/issues/123
> Prepare release 0.3

- cmd/qmstr/qmstr.go
- pkg/gnubuilder/asbuilder/asbuilder.go
- pkg/gnubuilder/asbuilder/asbuilder_test.go
- pkg/gnubuilder/gccbuilder/gcc-builder.go
- pkg/gnubuilder/gccbuilder/gcc-builder_test.go
closes https://github.com/QMSTR/qmstr-all/issues/140
> Add C++ support

- pkg/module/reporter/htmlreporter/share/skeleton/layouts/shortcodes/target-list.html
- pkg/reporting/bom.go
- proto/qmstr/service/bom.proto
closes https://github.com/QMSTR/qmstr-all/issues/145
> Html reporter shows path not name

- doc/Installation.md
* Mentions that protoc needs to be installed
* go get Go related protobuf lib & generator
> Update documentation with proper installation

- pkg/gnubuilder/flags.go
closes https://github.com/QMSTR/qmstr-all/issues/154
> Add missing --noexecstack flag in ld and as compilers

- cmd/modules/analyzers/pkg-analyzer/main.go
- cmd/modules/analyzers/scancode-analyzer/main.go
- cmd/modules/analyzers/spdx-analyzer/main.go
- cmd/modules/analyzers/test-analyzer/main.go
- pkg/arbuilder/arbuilder.go
- pkg/builder/builder.go
- pkg/database/dgraph.go
- pkg/database/dgraph_test.go
- pkg/database/fileNode.go
- pkg/database/packageNode.go
- pkg/gnubuilder/asbuilder/asbuilder.go
- pkg/gnubuilder/gccbuilder/gcc-builder.go
- pkg/gnubuilder/ldbuilder/ld-builder.go
- pkg/master/analyze.go
- pkg/master/common.go
- pkg/objcopybuilder/objcopybuilder.go
- pkg/reporting/bom.go
- proto/qmstr/service/datamodel.proto
- python/spdx-analyzer/spdxanalyzer/__main__.py
closes https://github.com/QMSTR/qmstr-all/issues/141 
test it with:
https://github.com/QMSTR/qmstr-demo/pull/57
https://github.com/endocode/siemens_compliance/pull/11
> Get rid of arbitrary strings in file types 

- pkg/common/fileutil.go
closes https://github.com/QMSTR/qmstr-all/issues/149
> Remove tmp files from the report

- cmd/modules/analyzers/spdx-analyzer/main.go
- cmd/modules/reporters/console-reporter/main.go
- pkg/master/analyze.go
- pkg/master/report.go
- pkg/module/reporter/consolereporter/consolereporter.go
closes https://github.com/QMSTR/qmstr-all/issues/158
closes https://github.com/QMSTR/qmstr-all/issues/162
> Change spdx analyzer format and create reporter to report the errors of the analyzer

- README.md
- doc/Getting-Started.md
- doc/Qmstr.yaml.md
This is a first documentation for the qmstr.yaml file.
Any feedback is welcome. 
It may needs some changes and to split some parts.
> Add qmstr.yaml documentation

- Gopkg.lock
- Gopkg.toml
- cmd/modules/reporters/spdx-reporter/main.go
- pkg/common/fileutil.go
- pkg/common/fileutil_test.go
- pkg/config/config_test.go
- pkg/config/validation.go
- pkg/module/reporter/spdxreporter/spdxreporter.go
The reporter will create a tag-value formatted SPDX document with all
mandatory fields filled out. Fields that QMSTR does not support are
marked with "NOASSERTION" and as tool adds new features these should be
reviewed.
> Introduce SPDX Reporter

- doc/tutorial/qmstr.yaml
> Fix spdx analyzer config

- Gopkg.lock
- cmd/modules/analyzers/spdx-analyzer/main.go
- pkg/database/dgraph.go
- pkg/database/dgraph_test.go
- pkg/database/diagnosticNode.go
- pkg/master/analyze.go
- pkg/master/common.go
- pkg/master/master.go
- pkg/module/reporter/consolereporter/consolereporter.go
closes https://github.com/QMSTR/qmstr-all/issues/171
> Introduce diagnostic nodes

- pkg/gnubuilder/gccbuilder/gcc-builder.go
- pkg/gnubuilder/ldbuilder/ld-builder.go
closes https://github.com/QMSTR/qmstr-all/issues/144
> ccache init

- doc/content/qmstr-basics/qmstr-cli/database_cmds/create/_index.md
- doc/content/qmstr-basics/qmstr-cli/database_cmds/delete/_index.md
- doc/content/qmstr-basics/qmstr-cli/database_cmds/describe/_index.md
- pkg/cli/describe.go
closes https://github.com/QMSTR/qmstr-all/issues/193
> Adapt qmstrctl describe to nodeid parsing

- pkg/cli/start.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/validation.go
- pkg/database/dgraph.go
- pkg/database/dgraph_test.go
- pkg/database/projectNode.go
- pkg/master/init.go
closes https://github.com/QMSTR/qmstr-all/issues/199
> Refactor init phase

- pkg/common/fileutil.go
- pkg/database/dgraph.go
- pkg/database/fileNode.go
- pkg/database/packageNode.go
- pkg/gnubuilder/gccbuilder/gcc-builder.go
- pkg/gnubuilder/ldbuilder/ld-builder.go
- pkg/service/common.go
closes https://github.com/QMSTR/qmstr-all/issues/197
> Distinguish between dependencies and inheritances

- pkg/cli/connect.go
- pkg/master/master.go
* FileNode to FileNode
* FileNode to PackageNode
> Connect command

- Makefile
Build the doc site and save the statics into a tar file.
> Add make docs command

- README.md
- doc/content/developer/_index.md
- doc/content/developer/dev-environment.md
Involves moving the development environment setup notes to a new "For Developers" documentation chapter.
Resolves #250.
> Update README to point to the new documentation pages.

- doc/config.toml
- doc/content/_index.md
- doc/content/configuration/_index.md
- doc/content/introduction/_index.md
- doc/content/introduction/getting-started/_index.md
- doc/content/introduction/installation/_index.md
- doc/content/introduction/what-is-qmstr.md
- doc/content/introduction/why-qmstr.md
- doc/layouts/partials/last-updated.html
...and only show the last modified date on the bottom of the content
> Use Git timestamps for last modified dates

- doc/content/WIP/_index.md
- doc/content/WIP/validation/_index.md
This PR adds the spec for the QMSTR validator that verifies the content of a package against the SPDX manifest.
> Add initial specification for the QMSTR validator.

- ci/test-documentation.sh
- doc/content/introduction/getting-started/tutorial/build-json-c.sh
- doc/content/introduction/getting-started/tutorial/qmstr.yaml
closes https://github.com/QMSTR/qmstr-all/issues/163
> Fix jsonc tutorial

- pkg/cli/describe.go
- pkg/service/common.go
closes https://github.com/QMSTR/qmstr-all/issues/205
> Extend describe command 

- Makefile
- doc/content/introduction/installation/_index.md
Updates both the Makefiles and the documentation.
> Remove use of GOPATH in Makefiles

- .gitignore
- Makefile
- ci/Makefile.common
- ci/vagrant-bootstrap.sh
- ci/vagrant-test-documentation-driver.sh
- clients/qmstrctl/Makefile.common
- doc/content/configuration/_index.md
- doc/content/developer/dev-environment.md
- doc/content/introduction/getting-started/_index.md
- doc/content/introduction/getting-started/tutorial/build-json-c.sh
- doc/content/introduction/getting-started/tutorial/qmstr.yaml
- doc/content/introduction/installation/_index.md
- go.mod
- go.sum
- lib/go-qmstr/service/Makefile.common
- masterserver/Dockerfile
- masterserver/Makefile.common
- modules/analyzers/spdx-analyzer/Makefile.common
... and fixing makefile dependencies
> update config documentation

- doc/content/introduction/getting-started/_index.md
- doc/content/introduction/getting-started/tutorial/qmstr.yaml
And create package with version.
> Remove git analyzer from the tutorial

- lib/go-qmstr/database/qmstrStateNode.go
- lib/go-qmstr/master/master.go
- lib/go-qmstr/reporting/package_data.go
- modules/reporters/qmstr-reporter-html/htmlreporter.go
- modules/reporters/qmstr-reporter-html/package_reports.go
- modules/reporters/qmstr-reporter-html/share/skeleton/layouts/shortcodes/licenses.html
- modules/reporters/qmstr-reporter-html/share/skeleton/layouts/shortcodes/target-list.html
- modules/reporters/qmstr-reporter-html/share/templates/site-index.md
- modules/reporters/qmstr-reporter-html/share/templates/version-index.md
Render author and license information
> extend html report

- lib/go-qmstr/cli/spawn.go
> Move the spawn sub-command to qmstrctl.

- Makefile
- ci/Vagrantfile
- ci/test-documentation.sh
- ci/vagrant-bootstrap.sh
- masterserver/Makefile.common
Introduce check for all commands to be available on PATH before starting
build in Makefile.
closes #327
> Check if required commands are available

- lib/go-qmstr/cli-qmstr/validate.go
> qmstr validate stub command

- masterserver/Dockerfile
> add protoc to builder

- lib/go-qmstr/arbuilder/arbuilder.go
- lib/go-qmstr/builder/builder.go
- lib/go-qmstr/cli-qmstr/run.go
- lib/go-qmstr/gnubuilder/asbuilder/asbuilder.go
- lib/go-qmstr/gnubuilder/gccbuilder/gcc-builder.go
- lib/go-qmstr/gnubuilder/ldbuilder/ld-builder.go
- lib/go-qmstr/master/build.go
- lib/go-qmstr/objcopybuilder/objcopybuilder.go
- lib/go-qmstr/objcopybuilder/objcopybuilder_test.go
- lib/go-qmstr/stripbuilder/stripbuilder.go
- lib/go-qmstr/stripbuilder/stripbuilder_test.go
- lib/go-qmstr/wrapper/wrapping.go
- modules/builders/qmstr-wrapper/qmstr-wrapper.go
> Change builder life cycle

- lib/go-qmstr/cli-qmstr/validate.go
- lib/go-qmstr/validation/errors.go
- lib/go-qmstr/validation/validation.go
- modules/manifests/spdx.go
* Introduce custom error with exit codes for each
* Introduce MissingLicenseInfoError & MissingCopyrightInfoError
closes #356 #360
> Update `qmstr validate` functionality

- modules/reporters/package-manifest-reporter/Makefile.common
- modules/reporters/package-manifest-reporter/main.go
- modules/reporters/package-manifest-reporter/pkg_manifestreporter.go
- modules/reporters/spdx-reporter/Makefile.common
> Rename spdx-reporter to package-manifest-reporter

- lib/go-qmstr/database/infoNode.go
- lib/go-qmstr/master/report.go
- modules/reporters/package-manifest-reporter/pkg_manifestreporter.go
- modules/reporters/qmstr-reporter-html/package_reports.go
closes https://github.com/QMSTR/qmstr/issues/353
> Extend manifest to print license and copyright information

- modules/manifests/spdx.go
- modules/reporters/package-manifest-reporter/pkg_manifestreporter.go
> Fix validation

- lib/java-qmstr/src/main/java/org/qmstr/grpc/service/Datamodel.java
- lib/java-qmstr/src/main/java/org/qmstr/util/FilenodeUtils.java
> Adapt java lib to the new database struct

- lib/go-qmstr/cli-qmstr/run.go
- lib/go-qmstr/database/dgraph.go
- lib/go-qmstr/database/diagnosticNode.go
- lib/go-qmstr/database/fileNode.go
- lib/go-qmstr/database/infoNode.go
- lib/go-qmstr/master/common.go
- lib/go-qmstr/service/common.go
- lib/go-qmstr/wrapper/wrapping.go
closes #409 
- Multiple files can have the same hash
- Describe cmd prints file did
- Remove panic
- Solve hash race condition
> Fix bugs based on the data structure PR

- go.sum
- lib/go-qmstr/database/dgraph.go
- lib/go-qmstr/database/dgraph_test.go
- lib/go-qmstr/database/diagnosticNode.go
- lib/go-qmstr/database/fileNode.go
- lib/go-qmstr/database/packageNode.go
> Remove convenience function

- doc/content/WIP/self-contained-modules/_index.md
Add first idea for self-contained modules.
> [doc wip] toward self contained modules

- modules/builders/qmstr-py-builder/qmstrpybuilder/bdistbuilder.py
connect bytecode and source files
> fix python bytecode

- .gitmodules
- Jenkinsfile
> Enable flask demo

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Introducing bug report and pull request template.
> Update issue templates
